# Site settings
title: Malware Analysis
baseurl: "cis700-f21"
url: "https://kmicinski.com/"
description: "CIS700--Special Topics in Computer Science, Malware Analysis, at Syracuse U"
permalink: pretty

# Build settings
#markdown: redcarpet

# Build posts to appear in the future
future: true

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
