# Site settings
title: CIS352
baseurl: "cis352-s21" #"cis352"
url: "http://kmicinski.com/"
description: "CMSC352--Principles of Programming Languages (Spring '21) at Syracuse"
permalink: pretty

# Build settings
#markdown: redcarpet

# Build posts to appear in the future
future: true

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
